---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" . }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: 6060
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "geth.selectorLabels" . | nindent 4 }}
