apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
{{ if and .Values.databases .Values.users }}
  userlist.txt: >
{{ include "userlist.txt" . | b64enc | indent 4 }}
{{ end }}
  pgbouncer.ini: >
{{ include "pgbouncer.ini" . | b64enc | indent 4 }}
