{{- if and (.Values.metrics.enabled) (.Values.metrics.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "geth.fullname" . }}
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "geth.fullname" . }}
  endpoints:
  - path: /debug/metrics/prometheus
    port: metrics
    {{- if .Values.metrics.serviceMonitor.interval }}
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "geth.selectorLabels" . | nindent 8 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end -}}



